CREATE TABLE curso(
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT NOT NULL
);

INSERT INTO curso (nome, descricao) VALUES ('EDIFICACOES', 'PEDREIRO'),
('INFORMATICA', 'TECNOLOGIA'),
('ELETROTECNICA', 'ELETRICIDADE'),
('SEGURANÇA DO TRABALHO', 'TRABALHO'),
('AUTOMACAO', 'MAQUINAS');